### ISSUE TITLE
Message incomplete

### ISSUE THREAD

**Issue by kosfango** [ykaliuta/fidogate#1]
Seems, if message has multi-part structure and if one of parts were lost:
/usr/local/fido/gate/bin/runinc missing: 21 Jun 16 03:20:44 @770/3       00000  02 / 02 message <> incomplete!

**Comment by ykaliuta** [comment]
Ok, there were some leftovers in the fidogate's spool. Why they appeared initially is not clear, but feel free to reopen the issue as soon as you can reproduce it.
