### ISSUE TITLE
Empty lines in headers

### ISSUE THREAD

**Issue by kosfango** [ykaliuta/fidogate#2]
If option -b is present in the areas config file, for example:
""                      fido.                   -8 -H -z 2 -b -a 2:5034/10.999
so during encoding, headers will contain additional empty lines:
[skip]
Organization: =?windows-1251?B?SODh7vAg7e7i+/Ug6+jt6u7iIC0gaHR0cDovL2FsdHluY2x1Yi5ydS9maWRv?=

 =?windows-1251?B?bmV0Lmh0bWwK?=
Lines: 13
X-Gateway: FIDO 5034.ru [FIDOGATE 5.2.4ds]
X-FTN-From: Dima Bargamov @ 2:5020/570.0
X-FTN-Flags: 
X-FTN-Tearline: GoldED-NSF (altyn.local)
X-FTN-Origin: =?windows-1251?B?SODh7vAg7e7i+/Ug6+jt6u7iIC0gaHR0cDovL2FsdHluY2x1Yi5ydS9maWRv?=

 =?windows-1251?B?bmV0Lmh0bWwgKDI6NTAyMC81NzApCg==?=
[skip]

as result it cause incorrect display messages in some newsreaders (for example Mozilla Thunderbird)

sniffer result:
http://s11.radikal.ru/i183/1701/b7/374f3dffab28t.jpg

**Comment by ykaliuta** [comment]
The fix is committed to master.
