### ISSUE TITLE
Exclude the carbon copy group for followups

### ISSUE THREAD

**Issue by evs38** [ykaliuta/fidogate#23]
I suggest to add into the messages that are copied to the carbon group the `Followup-To:` header in which there will be no carbon group included. This will make it possible to not crosspost in it when answering from the NNTP client.

**Comment by ykaliuta** [comment]
I'm so sorry, but could you elaborate on this?

**Comment by evs38** [comment]
Okay.
I have set up the CarbonNameGroup parameter in fidogate.conf:
`CarbonNameGroup Eugene_Subbotin local.cc`
So any messages from FTN which contains my name are crossposted into my local newsgroup just with adding it into the Newsgroups headers field:
`Newsgroups: fido.pushkin.local,local.cc`
I suggest to add in processing functions of carbon messages another header which doesn't contain the carbon newsgroup:
`Followup-To: fido.pushkin.local` (just retaining the original Newsgroups header without adding the carbon group).

**Comment by ykaliuta** [comment]
> Okay. I have set up the CarbonNameGroup parameter in fidogate.conf: `CarbonNameGroup Eugene_Subbotin local.cc` So any messages from FTN which contains my name are crossposted into my local newsgroup just with adding it into the Newsgroups headers field: `Newsgroups: fido.pushkin.local,local.cc` I suggest to add in processing functions of carbon messages another header which doesn't contain the carbon newsgroup: `Followup-To: fido.pushkin.local` (just retaining the original Newsgroups header without adding the carbon group).

Thanks! I'll check

**Comment by evs38** [comment]
Works correctly :)
