### ISSUE TITLE
Issue with charset.bin

### ISSUE THREAD

**Issue by kosfango** [ykaliuta/fidogate#3]
charset.bin was not overwritten after "make install" command

**Comment by ykaliuta** [comment]
Would it make sense to remove internal recoding completely in favour of iconv? It can map 8bit -> multibyte but not back.

**Comment by kosfango** [comment]
It will be sad if it break ftn2rfc (e.g. 866->uft8)

**Comment by ykaliuta** [comment]
Well, at the moment it works with iconv only since I cannot remember 866->utf8 internal table (even if it is possible in practice).

**Comment by kosfango** [comment]
How ftn2rfc works now? It seems no issues with gating echomail from fidonet

**Comment by ykaliuta** [comment]
With iconv I guess, it's enabled by default.

**Comment by kosfango** [comment]
> but not back.

I mean these words or it's about other things not for ftn2rfc?

**Comment by ykaliuta** [comment]
not utf8->8bits

**Comment by kosfango** [comment]
I think, in case of ftn2rfc, all modern nntp client software have uft8 support out of box and by default. In this case, it shouldn't be a disadvantage, but not for case rfc2ftn

**Comment by kosfango** [comment]
> not utf8->8bits

Does Fidogate gating rfc2ftn without iconv uft8->866 now?

**Comment by ykaliuta** [comment]
> > not utf8->8bits
> 
> Does Fidogate gating rfc2ftn without iconv uft8->866 now?

no

**Comment by ykaliuta** [comment]
The original issue should be fixed by 212d5aa85e9c
