### ISSUE TITLE
Problem with symbol "-" in echo name

### ISSUE THREAD

**Issue by kosfango** [ykaliuta/fidogate#7]
It seems, impossible to send message from nntp to ftn, if areaname contain "-" symbol.
E.g. 5020-723.LOCAL. Logs said:

Oct 11 14:20:06 ftntoss node 2:5034/10.999 not authorized to create area 5020|723.LOCAL (config restriction)
Oct 11 14:20:06 ftntoss unknown area 5020|723.LOCAL from 2:5034/10.999

However, the area aleady exist as 5020-723.LOCAL. Echomail from ftn to nntp looks good.

**Comment by ykaliuta** [comment]
Doesn't manual mapping in "areas" solve it?

**Comment by kosfango** [comment]
> Doesn't manual mapping in "areas" solve it?

Yes, I have next line in areas config:
5020-723.LOCAL          fido.5020-723.local     -8 -z 2 -b -a 2:5034/10.999

**Comment by ykaliuta** [comment]
With my configuration I cannot reproduce `-` to `|` conversion (config restriction is a totally different thing, configured by passwd file). I have (the default in the .sample):
```
# Translation of chars for automatic areas <-> newsgroup conversion
# (-H hierarchy option in AREAS)
#
#                       area chars      newsgroup chars
#                       ----------      ---------------
AreasXlate              &               \&
AreasXlate              $               \$
AreasXlate              '               \'
AreasXlate              /               \/
AreasXlate              |               \|
```
only related (no `-` here).
Is it still the issue (without the extra line in areas)?

**Comment by ykaliuta** [comment]
Ok, as discussed, it's just a misconfiguration.
